# quality-menu.conf
# Placement: ~~ /script-opts/quality-menu.conf

# Keep the menu clean: use predefined labels instead of fetching every format.
fetch_formats=no

quality_strings_video=[[{"2160p  (4K)": "bestvideo[height<=?2160][vcodec^=av01]+bestaudio/bestvideo[height<=?2160]+bestaudio"}, {"1440p": "bestvideo[height<=?1440][vcodec^=av01]+bestaudio/bestvideo[height<=?1440]+bestaudio"}, {"1080p  (AV1)": "bestvideo[height<=?1080][vcodec^=av01]+bestaudio"}, {"1080p  (VP9)": "bestvideo[height<=?1080][vcodec^=vp9]+bestaudio"}, {"1080p  (H.264)": "bestvideo[height<=?1080][vcodec^=avc1]+bestaudio"}, {"720p": "bestvideo[height<=?720][vcodec^=av01]+bestaudio/bestvideo[height<=?720]+bestaudio"}, {"480p": "bestvideo[height<=?480]+bestaudio"}, {"360p": "bestvideo[height<=?360]+bestaudio"}, {"Best available": "bestvideo+bestaudio/best"}]]
quality_strings_audio=[[{"Best audio": "bestaudio/best"}, {"128k": "bestaudio[abr<=128]/bestaudio"}, {"64k": "bestaudio[abr<=64]/bestaudio"}]]

# Keyboard / mouse controls
up_binding=UP WHEEL_UP
down_binding=DOWN WHEEL_DOWN
select_binding=ENTER MBTN_LEFT
close_menu_binding=ESC MBTN_RIGHT

selected_and_active=▶  
selected_and_inactive=▶  
unselected_and_active=✓  
unselected_and_inactive=   

style_ass_tags={\fnMontserrat ExtraBold\fs17\bord1}

shift_x=0
shift_y=0
text_padding_x=5
text_padding_y=8
scale_playlist_by_window=yes

curtain_opacity=0.4

menu_timeout=10

start_with_menu=no
include_unknown=no
hide_identical_columns=yes
